In [1]:
import librosa
import numpy as np
from glob import glob
#directories of normal audios
norm_data_dir = "C:\\Users\\Rahul\\Desktop\\proper\\hindi"
#norm_audio_files = glob(norm_data_dir + "*.wav")
audio_files = librosa.util.find_files(norm_data_dir , ext=['wav']) 
audio_files
audio_files=np.array(audio_files)

In [2]:
def trim(audio_files, top_db=10):
    clips = librosa.effects.trim(audio_files, top_db=10)
    return trim

In [3]:
import librosa
from librosa import feature
import numpy as np
fn_list_i = [
    feature.chroma_stft,
    feature.spectral_centroid,
    feature.spectral_bandwidth,
    feature.spectral_rolloff,
    feature.mfcc
]
 
fn_list_ii = [
    feature.zero_crossing_rate
]
def get_feature_vector(y,sr): 
    feat_vect_i = [ np.mean(funct(y,sr)) for funct in fn_list_i]
    feat_vect_ii = [ np.mean(funct(y)) for funct in fn_list_ii] 
    feature_vector = feat_vect_i + feat_vect_ii 
    return feature_vector

In [4]:
list = []
for file in audio_files:
    y , sr = librosa.load(file,sr=None,offset = 0.0,duration = 5.0)
    feature_vector = get_feature_vector(y, sr)
    list.append(feature_vector) 

In [5]:
import csv
norm_output = "hin_mfcc.csv"
header =[
 "chroma_stft",
 "spectral_centroid",
 "spectral_bandwidth",
 "spectral_rolloff",
    "mfcc"
 "zero_crossing_rate"
]
with open(norm_output,"+w") as f:
 csv_writer = csv.writer(f, delimiter = ",")
 csv_writer.writerow(header)
 csv_writer.writerows(list)


norm_output

'hin_mfcc.csv'

In [6]:
import pandas as pd
data= pd.read_csv('data.csv')
data

chroma_stft  spectral_centroid  spectral_bandwidth  spectral_rolloff  \
0       0.394742        4755.988562         3749.624053       9110.261643   
1       0.393535        4274.601618         3739.425234       8173.062768   
2       0.526681        2264.592481         2790.823169       4489.497173   
3       0.369277        4293.356353         4183.908119       8812.599947   
4       0.393160        4085.400607         3746.037956       8283.123662   
..           ...                ...                 ...               ...   
133     0.559090        6026.015425         5019.498324      11235.557700   
134     0.510231        4808.148575         4446.995224       9066.664446   
135     0.527142        5438.576141         4608.843404      10102.112210   
136     0.561517        6476.211360         5266.295211      12014.992000   
137     0.514901        5244.965529         4442.162893       9569.446295   

          mfcc  zero_crossing_rate     lang  
0   -14.881166            0.141730    Hindi  
1   -17.109806            0.119593    Hindi  
2   -10.644171            0.050359    Hindi  
3   -21.821318            0.104957    Hindi  
4   -15.232463            0.105658    Hindi  
..         ...                 ...      ...  
133 -20.632776            0.139485  English  
134 -18.059391            0.099329  English  
135 -17.637506            0.143430  English  
136 -23.405125            0.152984  English  
137 -17.807330            0.140177  English  

[138 rows x 7 columns]

In [7]:
# Importing the libraries
import numpy as np
import pandas as pd

In [8]:
import pandas as pd

Data1 = "C:\\Users\\Rahul\\Desktop\\proper\\hin_mfcc.csv"
Data2 = "C:\\Users\\Rahul\\Desktop\\proper\\mar_mfcc.csv"
Data3 = "C:\\Users\\Rahul\\Desktop\\proper\\eng_mfcc.csv"
files = [Data1,Data2,Data3]

# Combine all three CSV files using the concat method
data = pd.concat([pd.read_csv(f) for f in files])
# Export to csv
data.to_csv( "DATA.csv", index=False, encoding='utf-8-sig')
data = pd.read_csv("DATA.csv") 
data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Rahul\\Desktop\\proper\\hin_mfcc.csv'

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_data = le.fit_transform(data['lang'])
print(y_data)
X = data.iloc[:, 0:5].values
y = y_data         

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1, shuffle=True)
print(X_train)

[[ 4.51877470e-01  4.02632437e+03  3.88359125e+03  6.96618470e+03
  -2.23954810e+01]
 [ 4.45089760e-01  1.84840705e+03  2.67502904e+03  3.82237018e+03
  -2.24260600e+01]
 [ 5.33748300e-01  4.28362822e+03  4.00599090e+03  8.03106195e+03
  -1.47090160e+01]
 [ 3.93159630e-01  4.08540061e+03  3.74603796e+03  8.28312366e+03
  -1.52324630e+01]
 [ 5.27141700e-01  5.43857614e+03  4.60884340e+03  1.01021122e+04
  -1.76375060e+01]
 [ 4.98233020e-01  4.15125697e+03  3.92429063e+03  7.47161514e+03
  -1.49309470e+01]
 [ 3.98898500e-01  4.81141207e+03  4.26766630e+03  1.00866568e+04
  -1.83897130e+01]
 [ 4.87420350e-01  2.08755772e+03  2.58880618e+03  4.15061233e+03
  -8.95239100e+00]
 [ 4.36168640e-01  2.47316487e+03  3.10731035e+03  5.03891941e+03
  -1.05035220e+01]
 [ 4.77132200e-01  4.22515893e+03  3.76529216e+03  7.29371002e+03
  -1.72398720e+01]
 [ 5.54176600e-01  6.01436880e+03  4.86131373e+03  1.06371670e+04
  -2.61407150e+01]
 [ 4.01203130e-01  4.39389238e+03  4.11164655e+03  9.23922242e+03

In [5]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestClassifier 
 
 # create regressor object
classifier= RandomForestClassifier(n_estimators = 100, bootstrap=True,random_state = 1)
 
# fit the regressor with x and y data
classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=1)

In [35]:
# Applying PCA function on training
# and testing set of X component
from sklearn.decomposition import PCA
 
pca = PCA(n_components = 1)
 
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
 
explained_variance = pca.explained_variance_ratio_
X_train

array([[  611.81860474],
       [-3382.02512869],
       [ 1657.95609678],
       [ 1702.29652557],
       [ 4102.99201194],
       [ 1104.75364223],
       [ 3699.18260672],
       [-3019.51750713],
       [-1948.94621758],
       [  945.74804848],
       [ 4892.27364642],
       [ 2750.18017532],
       [-1354.05510894],
       [ -174.3084379 ],
       [ 4345.1666506 ],
       [-2595.85427057],
       [-3968.96709001],
       [  201.23691044],
       [-2610.53235635],
       [ 1863.32213385],
       [ 3593.20481896],
       [ 2270.22507626],
       [ 1535.53582881],
       [ 1093.37496345],
       [ 5613.63579649],
       [-2828.39974431],
       [ 3362.01540009],
       [-3320.874029  ],
       [-2397.85615405],
       [-2931.31828971],
       [-2452.73076393],
       [-2153.96007005],
       [ 4248.53588861],
       [-3615.75294772],
       [-2839.34667963],
       [ 3792.11260114],
       [-2489.39472679],
       [-3043.21492129],
       [ 4466.4899775 ],
       [-3469.40216592],


In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
#test harness 
seed=12
scoring='accuracy'

In [37]:
#load libraries
import pandas as pd
from pandas.plotting import scatter_matrix
from sklearn import model_selection
from sklearn.metrics import classification_report   
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
#check algorithm
models=[]
models.append(("LR",LogisticRegression()))
models.append(("LDA",LinearDiscriminantAnalysis()))
models.append(("KNN",KNeighborsClassifier()))
models.append(("CART",DecisionTreeClassifier()))
models.append(("RFC",RandomForestClassifier()))
models.append(("NB",GaussianNB()))
models.append(("SVM",SVC()))
#evaluate each model in turn
results=[]
names=[]
for name, model in models:
    kfold = model_selection.KFold(n_splits=5,shuffle=True,random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold,scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg="%s:%f(%f)"%(name,cv_results.mean(),cv_results.std())
    print(msg)
    

LR:0.581818(0.053009)
LDA:0.600000(0.034015)
KNN:0.672727(0.066804)
CART:0.609091(0.046355)
RFC:0.609091(0.046355)
NB:0.609091(0.046355)
SVM:0.672727(0.053009)


In [12]:
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestClassifier 
 
 # create regressor object
classifier= RandomForestClassifier(n_estimators = 100, bootstrap=True,random_state = 1)
 
# fit the regressor with x and y data
classifier.fit(X_train, y_train) 

NameError: name 'X_train' is not defined

In [6]:
y_pred = classifier.predict(X_train)
y_pred
classifier.score(X_test,y_test)

0.7857142857142857

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, classifier.predict(X_test))

TN = cm[0][0]
TP = cm[1][1]
FN = cm[1][0]
FP = cm[0][1]

print(cm)

print('Model Test Accuracy = {}'. format( (TP + TN )/ (TP + TN + FN + FP) ) )

[[4 1 0]
 [2 9 2]
 [1 0 9]]
Model Test Accuracy = 0.8125


In [5]:
import sounddevice as sd
import soundfile as sf
from tkinter import *


def Voice_rec():
    fs = 48000

    # seconds
    duration = 5
    myrecording = sd.rec(int(duration * fs),
      samplerate=fs, channels=2)
    sd.wait()

    # Save as FLAC file at correct sampling rate
    return sf.write('Audio.wav', myrecording, fs)


master = Tk()

Label(master, text=" Voice Recoder : "
    ).grid(row=0, sticky=W, rowspan=5)


b = Button(master, text="Start", command=Voice_rec)
b.grid(row=0, column=2, columnspan=2, rowspan=2,
    padx=5, pady=5)

mainloop()


In [8]:
import librosa
list = []
file="C:\\Users\\Rahul\\Desktop\\language recognition\\Audio1.wav"
y , sr = librosa.load(file,sr=None,offset = 0.0,duration = 5.0)
feature_vector = get_feature_vector(y, sr)
list.append(feature_vector) 

C:\Users\Rahul\AppData\Local\Temp\ipykernel_18916\2542418677.py:16: FutureWarning: Pass y=[ 0.0000000e+00 -1.5258789e-05  0.0000000e+00 ...  1.5258789e-05
 -1.5258789e-05  1.5258789e-05], sr=48000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  feat_vect_i = [ np.mean(funct(y,sr)) for funct in fn_list_i]


In [10]:
import csv
norm_output = "Input_audio.csv"
header =[
 "chroma_stft",
 "spectral_centroid",
 "spectral_bandwidth",
 "spectral_rolloff",
    "mfcc",
 "zero_crossing_rate"
]
with open(norm_output,"+w") as f:
    csv_writer = csv.writer(f, delimiter = ",")
    csv_writer.writerow(header)
    csv_writer.writerows(list)

import pandas as pd
Input= pd.read_csv('Input_audio.csv')
Input


Input=Input.loc[0].values.tolist()
Input

[0.61744523,
 6445.94053746282,
 5796.155909924951,
 12997.867803837951,
 -34.85783,
 0.1398118919909381]

In [44]:
 
pca = PCA(n_components = 1)
 
Input= pca.fit_transform(Input)
#Input= pca.transform(Input)
 
explained_variance = pca.explained_variance_ratio_
Input

C:\Users\Rahul\Anaconda3\envs\pratap\lib\site-packages\sklearn\decomposition\_pca.py:525: RuntimeWarning: invalid value encountered in true_divide
  explained_variance_ = (S**2) / (n_samples - 1)


array([[0.]])

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Input = sc.fit_transform(Input)
Input = sc.transform(Input)
Input

array([[0.]])

In [11]:
print(classifier.predict(([Input[0:5]])))

NameError: name 'classifier' is not defined